version: '1.0'
name: demo
displayName: demo
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
  schedule:
    - cron: '* 0 9 * * ? *'
stages:
  - name: task-spider
    displayName: task
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: gold_spider
        displayName: 金价爬取
        pythonVersion: '3.12'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - '# pip install --user -r requirements.txt'
          - python --version
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
