version: '1.0'
name: gold-spider
displayName: spider-demo
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
  schedule:
    - cron: '* 9 0 * * ? *'
stages:
  - name: stage1
    displayName: stage
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - '# pip install --user -r requirements.txt'
          - python --version
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
